# -*- coding: utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

base_url = 'http://10.1.0.56'
#
# classroom_para = [{"classroomname": u"30教室", "classaccnumber": "10"},
#                   {"classroomname": u"31教室", "classaccnumber": "10"},
#                   {"classroomname": u"33教室", "classaccnumber": "10"},
#                   {"classroomname": u"34教室", "classaccnumber": "10"},
#                   {"classroomname": u"38教室", "classaccnumber": "10"},
#                   {"classroomname": u"40教室", "classaccnumber": "10"},
#                   {"classroomname": u"81教室", "classaccnumber": "10"},
#                   {"classroomname": u"164教室", "classaccnumber": "10"}]
#
# equipment_para = [{'click_classroom': u'40教室',
#                    'equipment_name': u'10.1.0.40教室',
#                    'equipmentModel': u"Group系列",
#                    'ipAddr': '10.1.0.40',
#                    'locAddr': '10.1.0.40',
#                    'equipmentLogName': 'admin',
#                    'equipmentLogPwd': 'admin'},
#                   {'click_classroom': u'38教室',
#                    'equipment_name': u'10.1.0.38教室',
#                    'equipmentModel': u"Group系列",
#                    'ipAddr': '10.1.0.38',
#                    'locAddr': '10.1.0.38',
#                    'equipmentLogName': 'admin',
#                    'equipmentLogPwd': 'admin'},
#                   {'click_classroom': u'34教室',
#                    'equipment_name': u'10.1.0.34教室',
#                    'equipmentModel': u"Group系列",
#                    'ipAddr': '10.1.0.34',
#                    'locAddr': '10.1.0.34',
#                    'equipmentLogName': 'admin',
#                    'equipmentLogPwd': 'admin'},
#                   {'click_classroom': u'33教室',
#                    'equipment_name': u'10.1.0.33教室',
#                    'equipmentModel': u"Group系列",
#                    'ipAddr': '10.1.0.33',
#                    'locAddr': '10.1.0.33',
#                    'equipmentLogName': 'admin',
#                    'equipmentLogPwd': 'admin'},
#                   {'click_classroom': u'31教室',
#                    'equipment_name': u'10.1.0.31教室',
#                    'equipmentModel': u"Group系列",
#                    'ipAddr': '10.1.0.31',
#                    'locAddr': '10.1.0.31',
#                    'equipmentLogName': 'admin',
#                    'equipmentLogPwd': 'admin'},
#                   {'click_classroom': u'30教室',
#                    'equipment_name': u'10.1.0.30教室',
#                    'equipmentModel': u"Group系列",
#                    'ipAddr': '10.1.0.30',
#                    'locAddr': '10.1.0.30',
#                    'equipmentLogName': 'admin',
#                    'equipmentLogPwd': 'admin'}
#                   ]


classroom_para = [{"classroomname": u"10.3.98.58教室", "classaccnumber": "10"},
                  {"classroomname": u"10.3.98.57教室", "classaccnumber": "10"},
                  {"classroomname": u"10.3.98.56教室", "classaccnumber": "10"},
                  {"classroomname": u"10.3.98.55教室", "classaccnumber": "10"},
                  {"classroomname": u"10.3.98.54教室", "classaccnumber": "10"},
                  {"classroomname": u"10.3.98.53教室", "classaccnumber": "10"},
                  {"classroomname": u"10.3.98.52教室", "classaccnumber": "10"},
                  {"classroomname": u"10.3.98.51教室", "classaccnumber": "10"},
                  {"classroomname": u"10.3.98.50教室", "classaccnumber": "10"}]

equipment_para = [{'click_classroom': u'10.3.98.58教室',
                   'equipment_name': u'10.3.98.58教室',
                   'equipmentModel': u"Group系列",
                   'ipAddr': '10.3.98.58',
                   'locAddr': '10.3.98.58',
                   'equipmentLogName': 'admin',
                   'equipmentLogPwd': 'admin'},
                  {'click_classroom': u'10.3.98.57教室',
                   'equipment_name': u'10.3.98.57教室',
                   'equipmentModel': u"Group系列",
                   'ipAddr': '10.3.98.57',
                   'locAddr': '10.3.98.57',
                   'equipmentLogName': 'admin',
                   'equipmentLogPwd': 'admin'},
                  {'click_classroom': u'10.3.98.56教室',
                   'equipment_name': u'10.3.98.56教室',
                   'equipmentModel': u"Group系列",
                   'ipAddr': '10.3.98.56',
                   'locAddr': '10.3.98.56',
                   'equipmentLogName': 'admin',
                   'equipmentLogPwd': 'admin'},
                  {'click_classroom': u'10.3.98.55教室',
                   'equipment_name': u'10.3.98.55教室',
                   'equipmentModel': u"Group系列",
                   'ipAddr': '10.3.98.55',
                   'locAddr': '10.3.98.55',
                   'equipmentLogName': 'admin',
                   'equipmentLogPwd': 'admin'},
                  {'click_classroom': u'10.3.98.54教室',
                   'equipment_name': u'10.3.98.54教室',
                   'equipmentModel': u"Group系列",
                   'ipAddr': '10.3.98.54',
                   'locAddr': '10.3.98.54',
                   'equipmentLogName': 'admin',
                   'equipmentLogPwd': 'admin'},
                  {'click_classroom': u'10.3.98.53教室',
                   'equipment_name': u'10.3.98.53教室',
                   'equipmentModel': u"Group系列",
                   'ipAddr': '10.3.98.53',
                   'locAddr': '10.3.98.53',
                   'equipmentLogName': 'admin',
                   'equipmentLogPwd': 'admin'},
                  {'click_classroom': u'10.3.98.52教室',
                   'equipment_name': u'10.3.98.52教室',
                   'equipmentModel': u"Group系列",
                   'ipAddr': '10.3.98.52',
                   'locAddr': '10.3.98.52',
                   'equipmentLogName': 'admin',
                   'equipmentLogPwd': 'admin'},
                  {'click_classroom': u'10.3.98.51教室',
                   'equipment_name': u'10.3.98.51教室',
                   'equipmentModel': u"Group系列",
                   'ipAddr': '10.3.98.51',
                   'locAddr': '10.3.98.51',
                   'equipmentLogName': 'admin',
                   'equipmentLogPwd': 'admin'},
                  {'click_classroom': u'10.3.98.50教室',
                   'equipment_name': u'10.3.98.50教室',
                   'equipmentModel': u"Group系列",
                   'ipAddr': '10.3.98.50',
                   'locAddr': '10.3.98.50',
                   'equipmentLogName': 'admin',
                   'equipmentLogPwd': 'admin'}
                  ]
